"""
Pydantic models for API request / response validation.

These schemas mirror the TypeScript interfaces in the frontend
so that both ends stay in sync.
"""

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


# ── Enums ─────────────────────────────────────────────────────

class LixiType(str, Enum):
    K50 = "50k"
    K100 = "100k"
    K200 = "200k"
    K500 = "500k"
    SPECIAL = "special"


class FortuneMode(str, Enum):
    RANDOM = "random"
    TAI_LOC = "tai_loc"
    TINH_DUYEN = "tinh_duyen"
    SUC_KHOE = "suc_khoe"
    CONG_DANH = "cong_danh"
    GIA_DAO = "gia_dao"


class FortuneRating(int, Enum):
    BAD = 1
    AVERAGE = 2
    FAIR = 3
    GOOD = 4
    EXCELLENT = 5


# ── Wish (Lì Xì) ─────────────────────────────────────────────

class WishRequest(BaseModel):
    lixi_type: LixiType = Field(..., description="Mệnh giá lì xì")
    user_name: Optional[str] = Field(None, max_length=50, description="Tên người nhận (tuỳ chọn)")


class WishResponse(BaseModel):
    wish_text: str = Field(..., description="Lời chúc từ AI")
    lixi_type: LixiType


# ── Fortune (Quẻ) ────────────────────────────────────────────

class FortuneRequest(BaseModel):
    mode: FortuneMode = Field(FortuneMode.RANDOM, description="Lĩnh vực bốc quẻ")
    user_name: Optional[str] = Field(None, max_length=50, description="Tên người bốc (tuỳ chọn)")


class FortuneData(BaseModel):
    """Structured fortune content generated by AI."""
    title: str = Field(..., description="Tên quẻ (3-6 chữ Hán-Việt)")
    rating: FortuneRating = Field(..., description="Mức đánh giá 1-5")
    summary: str = Field(..., description="Tóm tắt 1 câu")
    detail: str = Field(..., description="Giải thích chi tiết")
    advice: str = Field(..., description="Lời khuyên")
    lucky_element: str = Field(..., description="Yếu tố may mắn")
    emoji: str = Field(..., description="Emoji đại diện")


class FortuneResponse(BaseModel):
    fortune: FortuneData
    mode: FortuneMode
    drawn_at: int = Field(..., description="Unix timestamp (ms)")


# ── Health ────────────────────────────────────────────────────

class HealthResponse(BaseModel):
    status: str = "ok"
    service: str = "ai-core"
